# Generated by Django 4.1.6 on 2023-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamersCave', '0002_post_answer_forum_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_post',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post_answer',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
