# Generated by Django 4.1.6 on 2023-02-13 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GamersCave', '0003_alter_forum_post_date_alter_post_answer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_answer',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='GamersCave.forum_post'),
        ),
    ]
